services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # 如果确认要使用自动扫描、自动注册，建议尽可能将要扫描的目录路径收缩，不要设置那么大的范围
  GiteeApiBundle\Command\:
    resource: '../../Command/'
  GiteeApiBundle\Controller\:
    resource: '../../Controller/'
  GiteeApiBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  GiteeApiBundle\Repository\:
    resource: '../../Repository/'
  GiteeApiBundle\Service\:
    resource: '../../Service/'

  # 为测试环境提供必需的服务  
  Symfony\Component\Routing\Generator\UrlGeneratorInterface:
    class: GiteeApiBundle\Tests\Service\MockUrlGenerator

  # 配置缓存实现（测试和开发环境）
  Psr\SimpleCache\CacheInterface:
    class: Symfony\Component\Cache\Psr16Cache
    arguments:
      - '@cache.array_adapter'

  cache.array_adapter:
    class: Symfony\Component\Cache\Adapter\ArrayAdapter

